groq:
  apiBaseUrl: https://api.groq.com/openai/v1
  model: llama-3.3-70b-versatile
  maxTokens: 400
  temperature: 0.2
  timeoutMillis: 8000

spring:
  main:
    allow-bean-definition-overriding: true