spring:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.2
          max-tokens: 400
app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 3600000
      issuer: "SIMADA"