# application.yml (padrão, comum a todos os perfis)
spring:
  ai:
    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.2
          max-tokens: 400

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:3600000} # 1h default
      issuer: ${JWT_ISSUER:WIKO}

server:
  port: ${PORT:8080}  # Render define PORT em runtime

---
# Perfil de PRODUÇÃO
spring:
  config:
    activate:
      on-profile: prod
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  app:
    front:
      url: ${APP_FRONT_URL:https://seu-front-no-vercel.vercel.app}
    mail:
      from: ${APP_MAIL_FROM}
    invite:
      ttl-days: ${APP_INVITE_TTL_DAYS:7}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc.time_zone: UTC
  flyway:
    enabled: true
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://simada-frontend.vercel.app/}
